import Foundation

/// The Home Screen icons the user can pick in Settings → App Icon. `primary`
/// is the default meow icon; every other case must have a matching
/// `.appiconset` in Assets.xcassets and be listed in
/// `ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES` (project.yml).
///
/// Every case also needs a `<rawValue>Preview.imageset` — the picker renders
/// artwork, not a text list, and `.appiconset` contents are not reliably
/// loadable through `UIImage(named:)` at runtime (the primary icon in
/// particular is not exposed under its asset name). The previews are
/// downscaled copies generated by `scripts/generate-app-icon.sh`.
enum AppIcon: String, CaseIterable, Identifiable {
    /// Default meow icon (`AppIcon.appiconset`).
    case primary = "AppIcon"
    /// Flat-style cat leaping over a brick wall (`AppIconLeap.appiconset`).
    case leap = "AppIconLeap"
    /// Calico kitten peeking over an ivy-covered wall at sunset
    /// (`AppIconSunset.appiconset`).
    case sunset = "AppIconSunset"
    /// Black cat resting on a moonlit wall (`AppIconMidnight.appiconset`).
    case midnight = "AppIconMidnight"

    var id: String {
        rawValue
    }

    /// Argument for `UIApplication.setAlternateIconName(_:)` — `nil` selects
    /// the primary icon.
    var alternateIconName: String? {
        self == .primary ? nil : rawValue
    }

    /// Asset-catalogue name of the imageset the picker renders as a tile.
    var previewAssetName: String {
        rawValue + "Preview"
    }

    /// Localizable.strings key for the display label in the picker.
    var titleKey: String {
        switch self {
        case .primary: "settings.appIcon.primary"
        case .leap: "settings.appIcon.leap"
        case .sunset: "settings.appIcon.sunset"
        case .midnight: "settings.appIcon.midnight"
        }
    }

    /// Maps `UIApplication.alternateIconName` back to a case. Unknown names
    /// (an icon dropped in an app update) fall back to `.primary`.
    init(alternateIconName: String?) {
        self = alternateIconName.flatMap(AppIcon.init(rawValue:)) ?? .primary
    }
}
